baseURL = "https://psoleckimoj.github.io/small-prs-presentation"
languageCode = "en-us"
title = "Writing small PRs"
theme = "reveal-hugo"

[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true
